name: My First Workflow

#trigger 
on: 
-push

# Jobs in the workflow
jobs:
# job name
  my-first-workflow:
  # OS that this workflow will be running on
  runs-on: ubuntu-latest

  # list of steps to perform task
  steps: 
  - name: echo the date
  # run commands are specific to the OS
  run: echo "The current time and date in Github is $(date)"